// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoazvnwiobtzzrdxjfzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYXp2bndpb2J0enpyZHhqZnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTU3NjEsImV4cCI6MjA1OTkzMTc2MX0.p10BKq5yZP0jNnVdylCp-AvG0vP_5ywBq7MxOAT_LjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);